// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuanLyTruongHoc.Infrastructure.Persistence;

#nullable disable

namespace QuanLyTruongHoc.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.BoMon", b =>
                {
                    b.Property<int>("MaBoMon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaBoMon"));

                    b.Property<int?>("MaKhoaVien")
                        .HasColumnType("integer");

                    b.Property<string>("TenBoMon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaBoMon");

                    b.HasIndex("MaKhoaVien");

                    b.ToTable("BoMons");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.DangKyLopHoc", b =>
                {
                    b.Property<int>("MaDangKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaDangKy"));

                    b.Property<int>("MaLopHocKy")
                        .HasColumnType("integer");

                    b.Property<int>("MaSinhVien")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaDangKy");

                    b.HasIndex("MaLopHocKy");

                    b.HasIndex("MaSinhVien", "MaLopHocKy")
                        .IsUnique();

                    b.ToTable("DangKyLopHocs");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.DiemHocPhan", b =>
                {
                    b.Property<int>("MaDangKy")
                        .HasColumnType("integer");

                    b.Property<decimal?>("DiemX")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<decimal?>("DiemY")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<decimal?>("DiemZ")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<DateTime?>("NgayNhapDiem")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MaDangKy");

                    b.ToTable("DiemHocPhans");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.DotDangKy", b =>
                {
                    b.Property<int>("MaDot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaDot"));

                    b.Property<bool>("ChoPhepDangKy")
                        .HasColumnType("boolean");

                    b.Property<bool>("ChoPhepRut")
                        .HasColumnType("boolean");

                    b.Property<string>("LoaiDot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaHocKy")
                        .HasColumnType("integer");

                    b.Property<int?>("MaKhoaVien")
                        .HasColumnType("integer");

                    b.Property<int?>("NamNhapHoc")
                        .HasColumnType("integer");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("MaDot");

                    b.HasIndex("MaHocKy");

                    b.HasIndex("MaKhoaVien");

                    b.ToTable("DotDangKys");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.GiangVien", b =>
                {
                    b.Property<int>("MaGiangVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaGiangVien"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MaBoMon")
                        .HasColumnType("integer");

                    b.Property<int?>("MaKhoaVien")
                        .HasColumnType("integer");

                    b.Property<int?>("MaTaiKhoan")
                        .HasColumnType("integer");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("text");

                    b.HasKey("MaGiangVien");

                    b.HasIndex("MaBoMon");

                    b.HasIndex("MaKhoaVien");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("GiangViens");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.HocKy", b =>
                {
                    b.Property<int>("MaHocKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaHocKy"));

                    b.Property<DateTime?>("HanDangKyDen")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("HanDangKyTu")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("HanRutDangKyDen")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("HanRutDangKyTu")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LoaiHocKy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaNamHoc")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateOnly>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<string>("TenHocKy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaHocKy");

                    b.HasIndex("MaNamHoc", "TenHocKy")
                        .IsUnique();

                    b.ToTable("HocKys");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.KetQuaHocTapKy", b =>
                {
                    b.Property<int>("MaSinhVien")
                        .HasColumnType("integer");

                    b.Property<int>("MaHocKy")
                        .HasColumnType("integer");

                    b.Property<decimal?>("GPAKy")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<decimal?>("GPATichLuyDenKy")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<int>("TinChiDangKyKy")
                        .HasColumnType("integer");

                    b.Property<int>("TinChiDatKy")
                        .HasColumnType("integer");

                    b.Property<int>("TinChiTichLuyDenKy")
                        .HasColumnType("integer");

                    b.HasKey("MaSinhVien", "MaHocKy");

                    b.HasIndex("MaHocKy");

                    b.ToTable("KetQuaHocTapKys");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.KhoaHocNganh", b =>
                {
                    b.Property<int>("MaKhoaHocNganh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaKhoaHocNganh"));

                    b.Property<int>("MaNganhHoc")
                        .HasColumnType("integer");

                    b.Property<int>("NamNhapHoc")
                        .HasColumnType("integer");

                    b.Property<string>("TenKhoaHoc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaKhoaHocNganh");

                    b.HasIndex("MaNganhHoc");

                    b.ToTable("KhoaHocNganhs");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.KhoaVien", b =>
                {
                    b.Property<int>("MaKhoaVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaKhoaVien"));

                    b.Property<string>("TenKhoaVien")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaKhoaVien");

                    b.HasIndex("TenKhoaVien")
                        .IsUnique();

                    b.ToTable("KhoaViens");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.KhungChuongTrinh", b =>
                {
                    b.Property<int>("MaKhungChuongTrinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaKhungChuongTrinh"));

                    b.Property<int>("MaNganhHoc")
                        .HasColumnType("integer");

                    b.Property<int>("SoTinChiBatBuoc")
                        .HasColumnType("integer");

                    b.Property<int>("SoTinChiTuChonToiThieu")
                        .HasColumnType("integer");

                    b.Property<int>("TongTinChi")
                        .HasColumnType("integer");

                    b.HasKey("MaKhungChuongTrinh");

                    b.HasIndex("MaNganhHoc")
                        .IsUnique();

                    b.ToTable("KhungChuongTrinhs");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.LichHocLopHocKy", b =>
                {
                    b.Property<int>("MaLich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaLich"));

                    b.Property<int>("MaLopHocKy")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateOnly>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<string>("PhongHoc")
                        .HasColumnType("text");

                    b.Property<int>("Thu")
                        .HasColumnType("integer");

                    b.Property<int>("TietBatDau")
                        .HasColumnType("integer");

                    b.Property<int>("TietKetThuc")
                        .HasColumnType("integer");

                    b.HasKey("MaLich");

                    b.HasIndex("MaLopHocKy");

                    b.ToTable("LichHocLopHocKys");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.LopHocKyGiangVien", b =>
                {
                    b.Property<int>("MaLopHocKy")
                        .HasColumnType("integer");

                    b.Property<int>("MaGiangVien")
                        .HasColumnType("integer");

                    b.Property<string>("VaiTro")
                        .HasColumnType("text");

                    b.HasKey("MaLopHocKy", "MaGiangVien");

                    b.HasIndex("MaGiangVien");

                    b.ToTable("LopHocKyGiangViens");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.LopHocTrongKy", b =>
                {
                    b.Property<int>("MaLopHocKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaLopHocKy"));

                    b.Property<string>("LoaiHinh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaHocKy")
                        .HasColumnType("integer");

                    b.Property<int>("MaMonHoc")
                        .HasColumnType("integer");

                    b.Property<int>("SiSoToiDa")
                        .HasColumnType("integer");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaLopHocKy");

                    b.HasIndex("MaHocKy");

                    b.HasIndex("MaMonHoc", "MaHocKy", "TenLop")
                        .IsUnique();

                    b.ToTable("LopHocTrongKys");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.MonHoc", b =>
                {
                    b.Property<int>("MaMonHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaMonHoc"));

                    b.Property<string>("LoaiMonHoc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MaBoMon")
                        .HasColumnType("integer");

                    b.Property<int?>("MaKhoaVien")
                        .HasColumnType("integer");

                    b.Property<int?>("MaMonHocTienQuyet")
                        .HasColumnType("integer");

                    b.Property<int>("SoTinChi")
                        .HasColumnType("integer");

                    b.Property<string>("TenMonHoc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaMonHoc");

                    b.HasIndex("MaBoMon");

                    b.HasIndex("MaKhoaVien");

                    b.HasIndex("MaMonHocTienQuyet");

                    b.ToTable("MonHocs");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.MonHocThuocKhungChuongTrinh", b =>
                {
                    b.Property<int>("Ma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Ma"));

                    b.Property<int>("KyHoc")
                        .HasColumnType("integer");

                    b.Property<int>("MaKhungChuongTrinh")
                        .HasColumnType("integer");

                    b.Property<int>("MaMonHoc")
                        .HasColumnType("integer");

                    b.HasKey("Ma");

                    b.HasIndex("MaMonHoc");

                    b.HasIndex("MaKhungChuongTrinh", "MaMonHoc")
                        .IsUnique();

                    b.ToTable("MonHocThuocKhungChuongTrinhs");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.NamHoc", b =>
                {
                    b.Property<int>("MaNamHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaNamHoc"));

                    b.Property<DateOnly>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateOnly>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<string>("TenNamHoc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaNamHoc");

                    b.HasIndex("TenNamHoc")
                        .IsUnique();

                    b.ToTable("NamHocs");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.NganhHoc", b =>
                {
                    b.Property<int>("MaNganh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaNganh"));

                    b.Property<int>("MaKhoaVien")
                        .HasColumnType("integer");

                    b.Property<string>("TenNganh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaNganh");

                    b.HasIndex("MaKhoaVien");

                    b.ToTable("NganhHocs");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.NhomLopNganh", b =>
                {
                    b.Property<int>("MaNhomLop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaNhomLop"));

                    b.Property<int?>("MaCoVanHocTap")
                        .HasColumnType("integer");

                    b.Property<int>("MaKhoaHocNganh")
                        .HasColumnType("integer");

                    b.Property<string>("TenNhomLop")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaNhomLop");

                    b.HasIndex("MaCoVanHocTap");

                    b.HasIndex("MaKhoaHocNganh");

                    b.ToTable("NhomLopNganhs");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.Quyen", b =>
                {
                    b.Property<int>("MaQuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaQuyen"));

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaQuyen");

                    b.HasIndex("TenQuyen")
                        .IsUnique();

                    b.ToTable("Quyens");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.SinhVien", b =>
                {
                    b.Property<int>("MaSinhVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaSinhVien"));

                    b.Property<decimal>("GPATichLuy")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("text");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaKhoaHocNganh")
                        .HasColumnType("integer");

                    b.Property<int?>("MaNhomLop")
                        .HasColumnType("integer");

                    b.Property<string>("MaSoSV")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MaTaiKhoan")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<int>("TongTinChiTichLuy")
                        .HasColumnType("integer");

                    b.HasKey("MaSinhVien");

                    b.HasIndex("MaKhoaHocNganh");

                    b.HasIndex("MaNhomLop");

                    b.HasIndex("MaSoSV")
                        .IsUnique();

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique();

                    b.ToTable("SinhViens");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<int>("MaQuyen")
                        .HasColumnType("integer");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("boolean");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("MaQuyen");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.TaiLieu", b =>
                {
                    b.Property<int>("MaTaiLieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaTaiLieu"));

                    b.Property<string>("GhiChuXuLy")
                        .HasColumnType("text");

                    b.Property<long>("KichThuocBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("LoaiTaiLieu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MaMonHoc")
                        .HasColumnType("integer");

                    b.Property<int>("MaNguoiTaiLen")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayTaiLen")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte[]>("NoiDungFile")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("SoTrang")
                        .HasColumnType("integer");

                    b.Property<string>("TenFile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenNguoiTaiLen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaTaiLieu");

                    b.HasIndex("MaMonHoc");

                    b.ToTable("TaiLieus");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.TaiLieuChunk", b =>
                {
                    b.Property<int>("MaChunk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaChunk"));

                    b.Property<int>("ChiSo")
                        .HasColumnType("integer");

                    b.Property<string>("Embedding")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaTaiLieu")
                        .HasColumnType("integer");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Trang")
                        .HasColumnType("integer");

                    b.HasKey("MaChunk");

                    b.HasIndex("MaTaiLieu");

                    b.ToTable("TaiLieuChunks");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.BoMon", b =>
                {
                    b.HasOne("QuanLyTruongHoc.Domain.Entities.KhoaVien", "KhoaVien")
                        .WithMany("BoMons")
                        .HasForeignKey("MaKhoaVien")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("KhoaVien");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.DangKyLopHoc", b =>
                {
                    b.HasOne("QuanLyTruongHoc.Domain.Entities.LopHocTrongKy", "LopHocTrongKy")
                        .WithMany("DangKyLopHocs")
                        .HasForeignKey("MaLopHocKy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyTruongHoc.Domain.Entities.SinhVien", "SinhVien")
                        .WithMany("DangKyLopHocs")
                        .HasForeignKey("MaSinhVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHocTrongKy");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.DiemHocPhan", b =>
                {
                    b.HasOne("QuanLyTruongHoc.Domain.Entities.DangKyLopHoc", "DangKyLopHoc")
                        .WithOne("DiemHocPhan")
                        .HasForeignKey("QuanLyTruongHoc.Domain.Entities.DiemHocPhan", "MaDangKy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DangKyLopHoc");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.DotDangKy", b =>
                {
                    b.HasOne("QuanLyTruongHoc.Domain.Entities.HocKy", "HocKy")
                        .WithMany()
                        .HasForeignKey("MaHocKy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyTruongHoc.Domain.Entities.KhoaVien", "KhoaVien")
                        .WithMany()
                        .HasForeignKey("MaKhoaVien")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("HocKy");

                    b.Navigation("KhoaVien");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.GiangVien", b =>
                {
                    b.HasOne("QuanLyTruongHoc.Domain.Entities.BoMon", "BoMon")
                        .WithMany("GiangViens")
                        .HasForeignKey("MaBoMon")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuanLyTruongHoc.Domain.Entities.KhoaVien", "KhoaVien")
                        .WithMany()
                        .HasForeignKey("MaKhoaVien")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuanLyTruongHoc.Domain.Entities.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("MaTaiKhoan");

                    b.Navigation("BoMon");

                    b.Navigation("KhoaVien");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.HocKy", b =>
                {
                    b.HasOne("QuanLyTruongHoc.Domain.Entities.NamHoc", "NamHoc")
                        .WithMany("HocKys")
                        .HasForeignKey("MaNamHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NamHoc");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.KetQuaHocTapKy", b =>
                {
                    b.HasOne("QuanLyTruongHoc.Domain.Entities.HocKy", "HocKy")
                        .WithMany()
                        .HasForeignKey("MaHocKy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyTruongHoc.Domain.Entities.SinhVien", "SinhVien")
                        .WithMany("KetQuaHocTapKys")
                        .HasForeignKey("MaSinhVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocKy");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.KhoaHocNganh", b =>
                {
                    b.HasOne("QuanLyTruongHoc.Domain.Entities.NganhHoc", "NganhHoc")
                        .WithMany("KhoaHocNganhs")
                        .HasForeignKey("MaNganhHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NganhHoc");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.KhungChuongTrinh", b =>
                {
                    b.HasOne("QuanLyTruongHoc.Domain.Entities.NganhHoc", "NganhHoc")
                        .WithOne("KhungChuongTrinh")
                        .HasForeignKey("QuanLyTruongHoc.Domain.Entities.KhungChuongTrinh", "MaNganhHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NganhHoc");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.LichHocLopHocKy", b =>
                {
                    b.HasOne("QuanLyTruongHoc.Domain.Entities.LopHocTrongKy", "LopHocTrongKy")
                        .WithMany("LichHocs")
                        .HasForeignKey("MaLopHocKy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHocTrongKy");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.LopHocKyGiangVien", b =>
                {
                    b.HasOne("QuanLyTruongHoc.Domain.Entities.GiangVien", "GiangVien")
                        .WithMany("LopHocKyGiangViens")
                        .HasForeignKey("MaGiangVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyTruongHoc.Domain.Entities.LopHocTrongKy", "LopHocTrongKy")
                        .WithMany("LopHocKyGiangViens")
                        .HasForeignKey("MaLopHocKy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiangVien");

                    b.Navigation("LopHocTrongKy");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.LopHocTrongKy", b =>
                {
                    b.HasOne("QuanLyTruongHoc.Domain.Entities.HocKy", "HocKy")
                        .WithMany("LopHocTrongKys")
                        .HasForeignKey("MaHocKy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyTruongHoc.Domain.Entities.MonHoc", "MonHoc")
                        .WithMany("LopHocTrongKys")
                        .HasForeignKey("MaMonHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocKy");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.MonHoc", b =>
                {
                    b.HasOne("QuanLyTruongHoc.Domain.Entities.BoMon", "BoMon")
                        .WithMany("MonHocs")
                        .HasForeignKey("MaBoMon")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuanLyTruongHoc.Domain.Entities.KhoaVien", "KhoaVien")
                        .WithMany()
                        .HasForeignKey("MaKhoaVien")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuanLyTruongHoc.Domain.Entities.MonHoc", "MonHocTienQuyet")
                        .WithMany()
                        .HasForeignKey("MaMonHocTienQuyet")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BoMon");

                    b.Navigation("KhoaVien");

                    b.Navigation("MonHocTienQuyet");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.MonHocThuocKhungChuongTrinh", b =>
                {
                    b.HasOne("QuanLyTruongHoc.Domain.Entities.KhungChuongTrinh", "KhungChuongTrinh")
                        .WithMany("MonHocThuocKhungChuongTrinhs")
                        .HasForeignKey("MaKhungChuongTrinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyTruongHoc.Domain.Entities.MonHoc", "MonHoc")
                        .WithMany("MonHocThuocKhungChuongTrinhs")
                        .HasForeignKey("MaMonHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhungChuongTrinh");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.NganhHoc", b =>
                {
                    b.HasOne("QuanLyTruongHoc.Domain.Entities.KhoaVien", "KhoaVien")
                        .WithMany("NganhHocs")
                        .HasForeignKey("MaKhoaVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhoaVien");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.NhomLopNganh", b =>
                {
                    b.HasOne("QuanLyTruongHoc.Domain.Entities.GiangVien", "CoVanHocTap")
                        .WithMany()
                        .HasForeignKey("MaCoVanHocTap")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuanLyTruongHoc.Domain.Entities.KhoaHocNganh", "KhoaHocNganh")
                        .WithMany("NhomLopNganhs")
                        .HasForeignKey("MaKhoaHocNganh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoVanHocTap");

                    b.Navigation("KhoaHocNganh");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.SinhVien", b =>
                {
                    b.HasOne("QuanLyTruongHoc.Domain.Entities.KhoaHocNganh", "KhoaHocNganh")
                        .WithMany()
                        .HasForeignKey("MaKhoaHocNganh")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyTruongHoc.Domain.Entities.NhomLopNganh", "NhomLopNganh")
                        .WithMany("SinhViens")
                        .HasForeignKey("MaNhomLop")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuanLyTruongHoc.Domain.Entities.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("MaTaiKhoan");

                    b.Navigation("KhoaHocNganh");

                    b.Navigation("NhomLopNganh");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.TaiKhoan", b =>
                {
                    b.HasOne("QuanLyTruongHoc.Domain.Entities.Quyen", "Quyen")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("MaQuyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quyen");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.TaiLieu", b =>
                {
                    b.HasOne("QuanLyTruongHoc.Domain.Entities.MonHoc", "MonHoc")
                        .WithMany()
                        .HasForeignKey("MaMonHoc")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.TaiLieuChunk", b =>
                {
                    b.HasOne("QuanLyTruongHoc.Domain.Entities.TaiLieu", "TaiLieu")
                        .WithMany("Chunks")
                        .HasForeignKey("MaTaiLieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiLieu");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.BoMon", b =>
                {
                    b.Navigation("GiangViens");

                    b.Navigation("MonHocs");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.DangKyLopHoc", b =>
                {
                    b.Navigation("DiemHocPhan");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.GiangVien", b =>
                {
                    b.Navigation("LopHocKyGiangViens");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.HocKy", b =>
                {
                    b.Navigation("LopHocTrongKys");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.KhoaHocNganh", b =>
                {
                    b.Navigation("NhomLopNganhs");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.KhoaVien", b =>
                {
                    b.Navigation("BoMons");

                    b.Navigation("NganhHocs");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.KhungChuongTrinh", b =>
                {
                    b.Navigation("MonHocThuocKhungChuongTrinhs");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.LopHocTrongKy", b =>
                {
                    b.Navigation("DangKyLopHocs");

                    b.Navigation("LichHocs");

                    b.Navigation("LopHocKyGiangViens");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.MonHoc", b =>
                {
                    b.Navigation("LopHocTrongKys");

                    b.Navigation("MonHocThuocKhungChuongTrinhs");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.NamHoc", b =>
                {
                    b.Navigation("HocKys");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.NganhHoc", b =>
                {
                    b.Navigation("KhoaHocNganhs");

                    b.Navigation("KhungChuongTrinh");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.NhomLopNganh", b =>
                {
                    b.Navigation("SinhViens");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.Quyen", b =>
                {
                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.SinhVien", b =>
                {
                    b.Navigation("DangKyLopHocs");

                    b.Navigation("KetQuaHocTapKys");
                });

            modelBuilder.Entity("QuanLyTruongHoc.Domain.Entities.TaiLieu", b =>
                {
                    b.Navigation("Chunks");
                });
#pragma warning restore 612, 618
        }
    }
}
